#!/bin/bash
#
# basic Arch install script
# by raehik
# 28/05/14
#

set -e

var_new_hostname=str1
var_timezone="/usr/share/zoneinfo/Europe/London"
var_net_profile=def-static
var_grub_disk=/dev/sda

pause_cont() {
    echo -n "(press Enter to continue)"
    #read dummy_var # necessary to work with sh
    read
}

echo "Uncomment the line #en_GB.UTF-8 UTF-8!"
pause_cont
vim /etc/locale.gen

echo "Running locale-gen..."
locale-gen

echo "Echoing LANG=en_GB.UTF-8 into new file /etc/locale.conf"
echo LANG=en_GB.UTF-8 > /etc/locale.conf

echo "Symlinking $var_timezone with /etc/localtime..."
ln -s $var_timezone /etc/localtime

echo "Setting hostname..."
echo $var_new_hostname > /etc/hostname
echo "On 127.0.0.1 line, add '$var_new_hostname' (your hostname) to the end!"
pause_cont
vim /etc/hosts

echo "Choose your password!"
passwd

echo "In HOOKS= line, add 'lvm2' between 'block' and 'filesystems'!"
echo "i.e. HOOKS="base udev autodetect modconf block lvm2 filesystems keyboard fsck""
pause_cont
vim /etc/mkinitcpio.conf
echo "Re-generating initramfs environment..."
mkinitcpio -p linux

echo "Moving network profile $var_net_prof_file to /etc/netctl/${var_net_prof_name}..."
mv /root/$var_net_profile /etc/netctl/

echo "Enabling that network profile on boot..."
netctl enable $var_net_profile

echo "Enabling SSH at boot..."
systemctl enable sshd

echo "Installing grub..."
grub-install --target=i386-pc --recheck $var_grub_disk
echo "Making grub config (don't worry about errors!)..."
grub-mkconfig -o /boot/grub/grub.cfg

echo "Exiting chroot..."
echo
exit
