#!/usr/bin/env bash
#
# Start install.
#

vars_file="vars"

# if not root, just end straight away
if [[ $(id -u) != 0 ]]; then
    echo "ERROR: not root"
    echo "Ending early so you don't eff anything up."
    exit 1
fi

# Source variable declarations.
#
# Refer to the file for variable names. All variables are prefixed with 'V_'.
source "$vars_file"

# if we're using tmux, re-run script if not in tmux already
if ! [[ $IN_CHROOT ]] && [[ "$V_use_tmux" ]] && [[ -z "$TMUX" ]]; then
    # 10/10 for recursion
    tmux new-session "$0"
    exit 0
fi

# Source helper functions. All functions are prefixed with '_'.
source lib/*

_log "helper functions sourced, install starting"

# Start install
## Pre-chroot {{{
if ! [[ $IN_CHROOT ]]; then
    _log "not in chroot, doing pre-chroot stuff"

    # run some modules
    _exec_module $V_M_disk
    _exec_module $V_M_base

    # now chroot in
    mkdir "/mnt/$V_chroot_tmp_dir/${PWD##*/}"
    cp -R "$PWD" "/mnt/$V_chroot_tmp_dir/${PWD##*/}"
    IN_CHROOT=yes arch-chroot /mnt /bin/bash -c "cd /$V_chroot_tmp_dir/${PWD##*/} ; ./${0##*/}"
else
## }}}
## In-chroot {{{
# if [[ $IN_CHROOT ]]; then
    _log "chrooted, running assorted modules"

    _exec_module $V_M_system_config
    _exec_module $V_M_network
    _exec_module $V_M_boot
    _exec_module $V_M_configs
fi
## }}}

